name: Terraform Apply and Destroy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'destroy'
        type: choice
        options:
          - destroy

permissions:
      id-token: write
      contents: read
jobs:
  terraform:
    name: Docker Build + Terraform Apply/Destroy
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: appoinment
      AWS_REGION: ap-south-1
      DOCKER_DIR: docker/appointment-service 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::495599733393:role/OIDC
          # role-to-assume: ${{ secrets.AWS_SECRET }}
          aws-region: ap-south-1


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR Repository Exists
        run: |
          aws ecr describe-repositories --repository-names "$IMAGE_NAME" || \
          aws ecr create-repository --repository-name "$IMAGE_NAME"

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME -f ${{ env.DOCKER_DIR }}/Dockerfile ${{ env.DOCKER_DIR }}

      - name: Tag Docker image
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:v1

      - name: Push Docker image to ECR
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker push $ECR_REGISTRY/$IMAGE_NAME:v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform validate 
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        if: contains(github.event.head_commit.message, 'terraform apply')
        run: terraform apply -auto-approve 

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve 
